### ISSUE TITLE
Find some way to support pure-Rust Wayland and X handles

### ISSUE THREAD

**Issue by ids1024** [rust-windowing/raw-window-handle#120]
Both wayland-rs and x11rb have pure-Rust backends that don't require C libraries for X or Wayland. But to use `raw-window-handle` it's necessary to use xcb/xlib/libwayland to have a pointer to put in the display and window handle.

Are there any good ways to support this? It *could* be supported with feature flags that pull in x11rb and wayland-rs as dependencies, but that is a bit problematic in terms of API stability.

This would generally be limited to software rendering (such as with softbuffer) since the EGL and Vulkan WSI implementations are written in C and use these C libraries. So its usefulness would be limited, but it would be nice to have.

**Comment by notgull** [comment]
I originally suggested something like this in #94, although its usefulness would be limited since it can't really be used in hardware acceleration... although maybe it could be used in `softbuffer`?

The question then becomes "how do we get the [`RustConnection`](https://docs.rs/x11rb/latest/x11rb/rust_connection/struct.RustConnection.html) to fit into a `RawDisplayHandle`?" The only answer I can come up with that doesn't involve `raw-window-handle` taking on extra dependencies would be to have the variant contain an `*const dyn Any` that can explicitly be downcasted to an `*const RustConnection`. The disadvantage of this would be that, if the program uses multiple versions of `x11rb`, that there could be a version mismatch between the windowing system and the rendering framework, which would cause confusing bugs.

The way I would prefer, from a `softbuffer` standpoint, would be to just have another constructor on the `Context` type that takes an `x11rb::RequestConnection` to circumvent this entire issue.

**Comment by notgull** [comment]
Between this and #102, it makes me wonder if there is a niche in the ecosystem for a more opinionated window handle type. Maybe an enum between the "raw" window handle defined in this crate (maybe even the [`WindowHandle`](https://docs.rs/raw-window-handle/latest/raw_window_handle/struct.WindowHandle.html) type to make it safer) and other more well-defined types?

**Comment by notgull** [comment]
My

**Comment by madsmtm** [comment]
Somewhat related: In https://github.com/rust-windowing/raw-window-handle/pull/134 we're doing _exactly_ this, exposing a pure Rust handle, without a stable ABI.

So we could probably adapt the same solution to this.

**Comment by notgull** [comment]
I would argue that #134 is an extenuating circumstance, since there are no other good ways to pass your canvas object to the underlying graphics APIs. Even the data attribute hack can only accommodate types currently registered in the DOM. So our hand is forced into exposing `wasm-bindgen`, even in an unstable way.

My stance on pure Rust desktop handles is the same as above. The expense of keeping pointers to them is greater than the possible benefits of letting `softbuffer` draw to them. Unless Mesa allows for `x11rb` or `wayland-rs` handles to be passed to EGL, it's probably a bad idea to include them.

**Comment by madsmtm** [comment]
> #134 is an extenuating circumstance

Yeah I probably exaggerated above, but I do think they share similarities, and that the solution we choose for `wasm-bindgen` _could_ be adapted for `x11rb`/`wayland-rs` as well.

> our hand is forced into exposing `wasm-bindgen`, even in an unstable way.

Well, we're never forced, we _could_ also take the choice you've done for this issue, and just... Not support web handles at all, until they get a stable ABI that we can use. But nobody wants that, and so we take another route ;)

**Comment by notgull** [comment]
The core issue is that `raw-window-handle` exists mostly as a layer between the graphics APIs (`glutin`, `wgpu`) and the windowing system (`winit`, SDL, `glfw`). Which in turn mostly deals with C pointers. Unless you happen to have a friend on the OpenGL ARB it's going to be difficult to pass a `wayland-rs` pure Rust implementation to `glutin` or `wgpu`. So the main use-case is really only `softbuffer`.

On the other hand, the graphics APIs as they are currently exposed to Rust take `wasm_bindgen::JsValue` or wrappers around `JsValue`. Hence the exposure of `JsValue`.

It might be nice to have some kind of other, broader crate with a more expansive window handle type, for crates that don't wrap around graphics APIs. But for a lot of existing crates that use `raw-window-handle`, like `winit`, do not want to have `x11rb` as a public dependency.

**Comment by madsmtm** [comment]
Makes sense. I'll leave this open anyhow until we figure out https://github.com/rust-windowing/raw-window-handle/pull/134, but will probably close it after that.

**Comment by notgull** [comment]
As of https://github.com/rust-windowing/softbuffer/pull/171 softbuffer can create a context and run without a C connection.

This issue was discussed in our weekly winit maintainer's meeting and it was decided that it's out of scope for `raw-window-handle`, especially since it's possible to work with just the window ID's. Closing this as not planned.
