### ISSUE TITLE
Possibility to query for platform without any generated window

### ISSUE THREAD

**Issue by Didgy74** [rust-windowing/raw-window-handle#19]
In some cases it can be beneficial to find out what platform the window is going to be running on before the actual window is created. An example when doing Vulkan and Qt interop:

The Qt application starts running, no window generated.
Query for which platform is running.
The Vulkan instance is generated using surface extensions dependant on the platform running.
The Vulkan code needs only load the surface function pointers for the platform in question
The window is generated using the Vulkan instance
Vulkan grabs the normal RawWindowHandle from the generated window.

This essentially means the Vulkan instance will only have to request the exact surface instance extensions upon creation, instead of safe-guarding by loading all the Linux surface extensions.

Qt requires a VkInstance to exist already to create QVulkanWindow, so this functionality would be nice.

**Comment by Lokathor** [comment]
I'm not a VK expert, but this is at least not the ordering that SDL2 uses, so I'm not sure if it's needed before window creation. In SDL2 you call [SDL_Vulkan_GetInstanceExtensions](https://wiki.libsdl.org/SDL_Vulkan_GetInstanceExtensions) _after_ you have an `SDL_Window` and _before_ you make a `VkInstance`.

I see the value in helping out VK the same as there's value in helping out GL, but making the crate not just be focused on some traits for different windows to implement really complicates the design. Does the SDL2 creation order where you make a window then query the window for how you should make your instance make sense for other window libs as well? If so, we should go with that, and then we can have a cargo feature that activates a trait for vulkan related stuff the same as we want to have a cargo feature for gl related stuff.

**Comment by Didgy74** [comment]
I can see that atleast GLFW does not require you to create a window before querying for instance extension: [GLFW - Querying required Vulkan extensions](https://www.glfw.org/docs/latest/vulkan_guide.html#vulkan_ext) Qt follows the same pattern. The pattern is basically:
```
Initialize windowing library (don't generate window)
Get platform info
Create instance
Create window
```
Where the last two steps are interchangeable in GLFW, but not in Qt.

Adopting this pattern might break compatibility with SDL, although when looking over the [link you provided](https://wiki.libsdl.org/SDL_Vulkan_GetInstanceExtensions) I can see that the `window` parameter is being deprecated in a future release:
```
window - A window for which the required Vulkan instance extensions should be retrieved (will be deprecated in a future release)
```

I will say, implementing this functionality for SDL2 or Winit can be impossible as neither seems to have any way to query platform info before creating. Implementing it for GLFW should be fairly simple, and any Rust bindings for Qt should be able to implement it. It should be possible to implement on SDL2 once that window parameter is deprecated, for Winit I can't say for sure.

**Comment by Lokathor** [comment]
Yeah it seems like there's 2 things here:

1) What you want isn't really related to communication between two libraries that both aren't end user libraries, which is kinda what this crate is about. Decoupling the connection between two separate non-end-user libraries so that there's less trouble when one of the two libraries updates. I think that the crate should stay _as small as possible_ so that we can sort out a good design for a 1.0 quality crate and then hopefully never even need a minor release (just patch releases).

2) If you have some sort of API Initialization token you can make this a trait on that token, which works for GLFW and eventually SDL2, but it _doesn't_ work for `winit` and I don't think it _ever_ would work for `winit` because they don't force you to initialize their API in any special way before you call the rest of their functions. You could _maybe_ make it a method on the WindowBuilder...? but that sounds kinda jank.

**Comment by Didgy74** [comment]
Alright, it seems the most compatible way to solve, on the Vulkan side, is to always request all the window-system extensions available, load all the corresponding and then just choosing which function pointers to use depending on the data provided by RawWindowHandle. This should only be a minor performance decrease can be run once during initialization of the Vulkan library, so that should be acceptable. I'm closing the issue.
