### ISSUE TITLE
Add HINSTANCE for win32

### ISSUE THREAD

**Issue by msiglreith** [rust-windowing/raw-window-handle#2]
Vulkan requires for surface creation at least a HWND and HINSTANCE handle.

**Comment by Osspial** [comment]
Is this necessary? I'm pretty sure you can call `GetModuleHandle(ptr::null()) as HINSTANCE` to get the `HINSTANCE` from anywhere in the program.

**Comment by msiglreith** [comment]
IIRC there is some discrepancy when the hwnd comes from an external library or something like that

**Comment by Osspial** [comment]
The only discrepancy I'm aware of is that when you call `GetModuleHandle` from a DLL, the module handle is from the parent executable, not from the DLL. Since Rust links downstream libraries directly into the executable that shouldn't cause any issues. I'd be surprised if that were an issue even with a Rust library compiled to a DLL, but I'd need to test that to know for sure.

**Comment by Ralith** [comment]
> Since Rust links downstream libraries directly into the executable that shouldn't cause any issues

Is this really an assumption we want to bake in? It's perfectly reasonable for people to manually dynamically load libraries containing rust code from both rust and foreign processes. If there was really never any case in which being explicit was necessary, I don't think it would be in the Vulkan interface.

**Comment by Osspial** [comment]
@Ralith Fair enough. I've submitted a PR to add `HINSTANCE` in #30.
