### ISSUE TITLE
Wayland EGL surface member

### ISSUE THREAD

**Issue by kvark** [rust-windowing/raw-window-handle#61]
Related to https://github.com/gfx-rs/gfx/pull/3545

Currently, RWH has the following information for a wayland window:
    - `surface`: A pointer to a `wl_surface`.
    - `display`: A pointer to a `wl_display`.

If one needs to create an EGL context for drawing on this window, they have to go through `wl_egl_create_surface`, which gets the `surface` as well as the window size, and returns a `wl_egl_window` pointer.

Problem is: RWH doesn't hold any information about the window size. So we are in a situation that on one side of the API we have a real window, and it has the size. And on the other side we have EGL, and it wants the window handle and the size. But in the middle, RWH loses the information about the size. It sounds like RWH isn't accomplishing its goal of abstracting the window in this case?

Note that this isn't a problem for Xlib. I suspect that's because an Xlib window knows about its size (like probably any other window in the RWH enumeration). So the Xlib window is closer to `wl_egl_window` than it is to `wl_surface`.

I want to stress that I have no experience with Wayland (or X11), and I'm just raising a concern and searching for more input about the solution here.

At first, I thought that maybe `wl_egl_window` field could be added to the Wayland variant of RWH. However, I realized that this isn't going to help, since `winit` doesn't necessarily want to create an EGL window. So if we want RWH to work, it needs to communicate the window size, at least for the Wayland variant.

**Comment by msiglreith** [comment]
Up to my understanding the graphics API is reponsible for attaching a buffer to the `wl_surface` and wayland is a bit special here as there are no restrictions on the dimensions of the buffer. A wayland surface in vulkan would also report any possible image extents from 0 to 0xFFFFFFFF as possible dimensions.

In the explicit case of EGL here I assume the egl surface creation could be deferred here to the actual swapchain creation in gfx-rs.

**Comment by kchibisov** [comment]
Adding sizes won't help you in general, since you'd have an API to resize the window. Also in case of abstracting EGL your API will likely have some kind of notion to passing the size of the window, since you'd need the sizes for e.g. pbuffers on X11.

On Wayland EGL bootstrapping mostly all the time looks like that:

1. You create a connection to `WAYLAND_DISPLAY` and wl_display object.
2. You create EGLDisplay out of `wl_display`.
3. At this point you can pickup EGLConfig, though you can create a wayland window, doens't really matter.
4. Create Window to obtain wl_surface.
5. Given that on Wayland clients decide what the buffer size should be they can create wl_egl_surface, however once you pass this wl_egl_surface somewhere it's neither send nor sync, since mesa will attach its callbacks to it and will call to it, so if you resize it you'll call to mesa and it could mess up threads, so in general the `wl_egl_window` must be consumed by the underlying graphics API.
6. After that if you get resize event you should use that `wl_egl_window` to resize, but for example winit can't do that, since it must be done from a thread the `EGLSurface` is on (and it's neither `Send` nor `Sync` either).

So in general `wl_egl_window` shouldn't be exposed in anyway, since it's a special, not thread safe handle to a `egl_window`.

Passing sizes also doesn't make sense, since it's required by some other platform APIs as well, and various platforms like macOS also has a concept of update GL state after resize, which you should call (you need to resize context after the window attached to it got resized).

So in your case for Wayland, just use sizes you plan to use with e.g. winit, etc. You're not limited on what to provide, except passing zeros.
